alias xcp='xclip -in -sel c'
alias gcp="xclip -out -sel c"
alias gdbui='gdb -tui --nx -q'
alias pudb='python3 -m pudb'
alias vg='valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --num-callers=20 --track-fds=yes'
alias open='xdg-open'
alias cls='clear'
alias ta='tmux attach'
alias tn='tmux new -s main'
alias tx='pkill -USR1 tmux'
alias u='umask 0022'
alias cme='crackmapexec'
alias rdp='xfreerdp /w:1920 /h:1080 /smart-sizing /f'
alias venv='python3 -m venv venv'
alias lcp='cp -t ~/shares/shared_kali/OSEP/exam'
